ASSETS = 
  "entaRight": "assets/image/entaRight.png"
  "entaLeft": "assets/image/entaLeft.png"
  "sky": "assets/image/sky.png"
  "skyNogu": "assets/image/skyNogu.png"
  "ground": "assets/image/ground.png"
  "tina": "assets/image/tina.png"
  "title": "assets/image/title.png"
  "titleButton": "assets/image/btn.png"
  "titleBack": "assets/image/bg.png"
  "playButton": "assets/image/playButton.png"
  "bgm" : "assets/sound/bgm.mp3"
  "tutorial" : "assets/image/setumeiLead.png"
  "gameScoreBackground": "assets/image/header1.png"
  "itemTimer": "assets/image/timer.png"
