SCREEN_WIDTH = 640
SCREEN_HEIGHT = 960
SCREEN_CENTER_X = SCREEN_WIDTH/2
SCREEN_CENTER_Y = SCREEN_HEIGHT/2

PLAYER_WIDTH = 298
PLAYER_HEIGHT = 358
PLAYER_SCALE_FACTOR = 2.0
PLAYER_POSITION_Y = SCREEN_HEIGHT - PLAYER_HEIGHT/PLAYER_SCALE_FACTOR - 60

BALLOON_WIDTH = 469
BALLOON_HEIGHT = 349
LIMIT_BALLOONS = 8
ENEMY_WIDTH  = 161
ENEMY_HEIGHT = 156
ENEMY_SCALE_FACTOR = 2.0

GAME_LIMIT_TIMER = 30
