score = 0
gameTimer = 60
enableController = false
enemyTimer = 60
extraTimerFrequency = Math.rand 250, 300
balloonFrequency = Math.rand 100, 150
bgmPlayed = false
worldSpeed = 0.0
itemBalloonFlag = true
